# Generated by Django 5.2.5 on 2025-08-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_alter_fixtures_matchdate_alter_fixtures_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixtures',
            old_name='matchDate',
            new_name='matchDateTime',
        ),
    ]
