# Generated by Django 5.2.5 on 2025-08-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_rename_matchdate_fixtures_matchdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/team_logos/'),
        ),
    ]
