# Generated by Django 5.2.5 on 2025-08-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_rename_awayteam_fixtures_away_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixtures',
            options={'ordering': ['match_date_time']},
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
