# Generated by Django 5.2.5 on 2025-08-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_team_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixtures',
            name='actualAwayScore',
        ),
        migrations.RemoveField(
            model_name='fixtures',
            name='actualHomeScore',
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_home_score', models.IntegerField()),
                ('actual_away_score', models.IntegerField()),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='match.fixtures')),
            ],
        ),
    ]
