# Generated by Django 5.2.5 on 2025-08-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_remove_fixtures_actualawayscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtures',
            name='matchDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='status',
            field=models.CharField(default='upcoming', max_length=20),
        ),
    ]
