# Generated by Django 5.2.5 on 2025-08-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_alter_team_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixtures',
            old_name='awayTeam',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='fixtures',
            old_name='homeTeam',
            new_name='home_team',
        ),
        migrations.RenameField(
            model_name='fixtures',
            old_name='matchDateTime',
            new_name='match_date_time',
        ),
    ]
