# Generated by Django 5.2.5 on 2025-08-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_alter_fixtures_options_delete_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='external_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
